[package]
edition = "2021"
name    = "migration"
publish = false
version = "0.0.0"

[dependencies]
async-std         = { version = "1", features = ["attributes", "tokio1"] }
sea-orm-migration = { version = "0.11.0", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
