[package]
edition = "2021"
name = "spotify-backup"
version = "0.0.0-prerelease"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
codegen-units = 1
debug = 1
lto = "fat"
overflow-checks = true

[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "eeec6f0654f32270aec4e4a0d0f42e4ad39bc28e" }
axum = "^0.6"
color-eyre = "^0.6"
dotenvy = "^0.15"
envy = "^0.4"
futures = "0.3.25"
git-version = "^0.3"
lettre = { version = "^0.10", default-features = false, features = ["builder", "hostname", "pool", "smtp-transport", "tokio1-rustls-tls"] }
octocrab = { version = "^0.17", default-features = false, features = ["rustls", "stream"] }
rspotify = { version = "^0.11", default-features = false, features = ["client-reqwest", "reqwest-rustls-tls"] }
serde = { version = "^1.0", features = ["derive"] }
sqlx = { version = "^0.6", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "^1.21", features = ["full", "tracing"] }
tower = { version = "^0.4" }
tower-http = { version = "0.3.4", features = ["compression-br", "cors", "fs", "request-id", "sensitive-headers", "timeout", "trace"] }
tracing = "^0.1"
tracing-error = "0.2.0"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
