[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12", features = ["macros"] }
lambda_runtime = "0.4"
lambda_http = "0.4"
serde_json = "1.0"
log = "0.4"
simplelog = "0.10"
rspotify = { version = "0.11", default-features = false, features = [
    "client-reqwest",
    "reqwest-rustls-tls",
] }
