[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.10", features = ["tokio1"] }
csv = "1.1"
dotenv = "0.15"
flume = "0.10"
git2 = "0.13"
hyper = { version = "0.14", features = ["server"] }
indoc = "1.0"
rspotify = { version = "0.11", features = ["env-file"] }
tracing = "0.1"
tracing-subscriber = "0.2"
webbrowser = "0.5"

[profile.release]
lto = "fat"
