[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[profile.release]
lto = "fat"

[dependencies]
argh = "0.1"
async-std = { version = "1.10", features = ["tokio1"] }
color-eyre = { version = "0.5", default-features = false }
csv = "1.1"
dotenv = "0.15"
flume = "0.10"
git2 = "0.13"
hyper = { version = "0.14", features = ["server"] }
indoc = "1.0"
rspotify = { version = "0.11", features = ["reqwest-rustls-tls"] }
temp-dir = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
webbrowser = "0.5"

[patch.crates-io]
rspotify = { git = "https://github.com/DusterTheFirst/rspotify", branch = "patch-1" }
