[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = true
debug = 1

[dependencies]
askama = "0.11.1"
axum = "0.5.16"
color-eyre = "0.6.2"
dotenv = "0.15.0"
envy = "0.4.2"
octocrab = "0.17.0"
rspotify = { version = "0.11.5", default-features = false, features = [
    "client-reqwest",
    "reqwest-rustls-tls",
] }
serde = { version = "1.0.144", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["sqlite"] }
tokio = { version = "1.21.1", features = ["full", "tracing"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace", "fs", "cors"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
