[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2018"

[dependencies]
rspotify = "0.11"
csv = "1.1"
git2 = "0.13"
tracing = "0.1"
tracing-subscriber = "0.2"
dotenv = "0.15.0"
anyhow = "1.0.44"
async-std = { version = "1.10.0", features = ["tokio1"] }

[profile.release]
lto = "fat"
