[package]
name = "spotify-backup"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[profile.release]
lto = "fat"

[dependencies]
argh = "0.1"
async-std = { version = "1.10", features = ["tokio1"] }
color-eyre = { version = "0.5", default-features = false }
csv = "1.1"
dotenv = "0.15"
envy = "0.4"
flume = "0.10"
git2 = { version = "0.13", features = [
    "vendored-openssl",
    "https",
], default-features = false }
hyper = { version = "0.14", features = ["server"] }
indoc = "1.0"
rspotify = { version = "0.11", features = [
    "client-reqwest",
    "reqwest-rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
temp-dir = "0.1"
time = { version = "0.3", features = ["formatting", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
webbrowser = "0.5"

[patch.crates-io]
rspotify = { git = "https://github.com/ramsayleung/rspotify", rev = "b82c1ff3f3128c168acda3b72a30012755a456be" }
