[package]
edition = "2021"
name = "spotify-backup"
version = "0.0.0-prerelease"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
codegen-units = 1
debug = 1
lto = "fat"
overflow-checks = true

[dependencies]
askama = "^0.11"
axum = "^0.6"
color-eyre = "^0.6"
dotenv = "^0.15"
envy = "^0.4"
git-version = "0.3.5"
octocrab = "^0.17"
rspotify = { version = "^0.11", default-features = false, features = ["client-reqwest", "reqwest-rustls-tls"] }
serde = { version = "^1.0", features = ["derive"] }
sqlx = { version = "^0.6", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "^1.21", features = ["full", "tracing"] }
tower = "^0.4"
tower-http = { version = "^0.3", features = ["cors", "fs", "trace", "catch-panic"] }
tracing = "^0.1"
tracing-error = "0.2.0"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
