app = "spotify-backup"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
BIND = "0.0.0.0:8080"
DOMAIN = "backup.spotify.dusterthefirst.com"
SPOTIFY_CLIENT_ID = "be256626b1c24fc981ca6ed2c29b012f"

[deploy]
strategy = "canary"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 500
soft_limit = 450
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
grace_period = "5s"
interval = "10s"
method = "get"
path = "/api/healthy"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = false