app = "spotify-backup"
primary_region = "ams"

[env]
RUST_LOG = "info,tower_http=debug,spotify_backup=debug,axum::rejection=trace,rspotify=warn"

BIND   = "[::]:8080"
DOMAIN = "backup.spotify.dusterthefirst.com"

SPOTIFY_CLIENT_ID    = "be256626b1c24fc981ca6ed2c29b012f"
SPOTIFY_REDIRECT_URI = "https://backup.spotify.dusterthefirst.com/login/spotify"

SURREAL_ENDPOINT="spotify-backup-database.internal:8080"

[deploy]
strategy = "canary"

[[services]]
internal_port = 8080
protocol      = "tcp"

[services.concurrency]
hard_limit = 500
soft_limit = 450
type       = "connections"

[[services.ports]]
force_https = true
handlers    = ["http"]
port        = 80

[[services.ports]]
handlers = ["http", "tls"]
port     = 443

[[services.tcp_checks]]
grace_period  = "1s"
interval      = "15s"
restart_limit = 0
timeout       = "2s"

[[services.http_checks]]
grace_period    = "5s"
interval        = "10s"
method          = "get"
path            = "/health"
protocol        = "http"
restart_limit   = 0
timeout         = "2s"
tls_skip_verify = false

[services.http_checks.headers]
x-forwarded-host = "backup.spotify.dusterthefirst.com"
