org: dusterthefirst
app: spotify-backup
service: spotify-backup

provider:
  name: aws
  runtime: rust
  memorySize: 128
  region: us-east-1
  stage: dev
  lambdaHashingVersion: 20201221

package:
  individually: true

plugins:
  - serverless-rust

custom:
  rust:
    dockerless: true

env:
  RSPOTIFY_CLIENT_ID: ${param:spotify_client_id}
  RSPOTIFY_CLIENT_SECRET: ${param:spotify_client_secret}

functions:
  backup:
    handler: spotify-backup.backup
    events:
      - schedule: cron(0 0 * * ? *)
  seed:
    handler: spotify-backup.auth
    events:
      - http:
          path: /
          method: get
      - http:
          path: /login
          method: get