name = "spotify-backup"
main = "src/index.ts"
compatibility_date = "2022-05-22"

account_id = "90d15a1372995fa5ca0b476c1addce38"
usage_model = "bundled"
workers_dev = false
# route = { pattern = "spotify-backup.dusterthefirst.com/*", zone_id = "c3c0473cff588d953e94751745d61334" }

# minify = true

[triggers]
crons = ["0 * * * *"]

[vars]
SPOTIFY_CLIENT_ID = "be256626b1c24fc981ca6ed2c29b012f"

[[kv_namespaces]]
binding = "SPOTIFY_BACKUP_KV"
id = "0614fc5d79c54158b568522d602d08bc"
preview_id = "e04ae54277dd4ee1808c12c228c6e3b7"
