name: Build and deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust 1.56
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.56
          default: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --release --all-features --verbose

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "CI Build"
          files: |
            target/release/spotify-backup
